language: python
python: 3.8

jobs:
  include:
    - python: '3.8'
    - python: '3.7'
    - python: '3.6'

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  - cd pur_beurre/
  - wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/build/zetsumeishi/OC-Project-8/pur_beurre/

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py format_csv
  - python manage.py import_csv
  - coverage run -m manage test

after_success:
  - coveralls
