language: python
python: 3.8

sudo: required

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  - sudo apt install google-chrome-stable
  - wget https://chromedriver.storage.googleapis.com/72.0.3626.69/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8.0/bin/
  - export CHROME_DRIVER="chromedriver"

script:
  - python manage.py makemigrations  --settings="pur_beurre.test_settings"
  - python manage.py migrate --settings="pur_beurre.test_settings"
  - coverage run -m manage test --settings="pur_beurre.test_settings"

after_success:
  - coveralls
