language: python
python: 3.8

sudo: required

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_script:
  - sudo apt install google-chrome-stable
  - wget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8.0/bin/
  - export CHROME_DRIVER="chromedriver"
  - cd pur_beurre/

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py format_csv
  - python manage.py import_csv
  - coverage run -m manage test

after_success:
  - coveralls
